### ISSUE TITLE
Submit my fork to grails.org?

### ISSUE THREAD

**Issue by kensiprell** [burtbeckwith/grails-drools#2]
Burt,

I’ve forked your plugin (https://github.com/kensiprell/grails-drools) and made some major changes. I’d like to submit it to grails.org with your approval. I’m going to use it in a project, and I plan on maintaining it. Is that alright with you? Although you don’t need the street cred, I’ll leave you as an author if you approve

I still have a bunch of TODOs that I plan to finish over the next couple of days, and I’d appreciate any tips or suggestions.

Is is reasonable to ask to have this one replace the old one (http://grails.org/plugin/drools)? 

Ken

**Comment by burtbeckwith** [comment]
That would be great - having a maintainer who actually uses the plugin is generally a good thing :)
