### ISSUE TITLE
Request input before plugin release. I'm not happy.

### ISSUE THREAD

**Issue by kensiprell** [burtbeckwith/grails-drools#3]
I’d hoped to have this released by now. I was traveling with a very slow Internet connection, and Ivy couldn’t download the dependencies, so I didn’t find out that Grails 2.0.4 and 2.1.5 weren’t working until I returned home. Right now this is all I can get to work:
- Drools 6.2.0.CR4 (Grails versions 2.3.9 and 2.4.4)
- Drools 6.1.0.Final (Grails version 2.2.4)

If you think these limits are alright, I'll live with it. However, I’d like to have Grails 2.0 and up working, but I can’t figure out the `ClassNotFoundException` error (details below). If you have a tip or two on where I should look or what I should try, I'd appreciate it.

Is there a way for a user to get the plugin working with Grails 2.2.4 and older without having to insert the drools and kie dependencies block in his BuildConfig.groovy? I’ve thought about trying to do it programmatically, but I’m not sure if it’s possible or even worthwhile. Excluding the explicit Spring dependencies in `kie-spring`(https://repo1.maven.org/maven2/org/kie/kie-spring/6.2.0.CR4/kie-spring-6.2.0.CR4.pom) would be the easiest way, but that doesn't seem to be possible. 

Here’s how I’m running the functional tests, but 2.0.4 has been such a problem, I’ve been testing it manually: https://github.com/kensiprell/grails-plugin-test-script/blob/master/drools.sh.

Grails 2.0.4 and 2.1.5:
First this runtime error even though KieModuleCache$KModuleCache is on the classpath:

```
| Error 2015-01-23 19:46:22,489 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - ClassNotFoundException occurred when processing request: [GET] /grails-drools-sample/
org.drools.compiler.kie.builder.impl.KieModuleCache$KModuleCache. Stacktrace follows:
Message: org.drools.compiler.kie.builder.impl.KieModuleCache$KModuleCache
    Line | Method
->>  366 | run                       in java.net.URLClassLoader$1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    355 | run                       in     ''
|    354 | findClass . . . . . . . . in java.net.URLClassLoader
|    425 | loadClass                 in java.lang.ClassLoader
|    358 | loadClass . . . . . . . . in     ''
|    103 | createCacheBuilder        in org.drools.compiler.kie.builder.impl.KieMetaInfoBuilder
|     56 | generateKieModuleMetaInfo in     ''
|     38 | writeKieModuleMetaInfo    in     ''
|    178 | buildAll . . . . . . . .  in org.drools.compiler.kie.builder.impl.KieBuilderImpl
|    149 | buildKieBase              in grails.plugin.drools.DroolsService
|    125 | execute . . . . . . . . . in     ''
|     61 | executeFromFile           in     ''
|     53 | getModel . . . . . . . .  in grails.plugin.drools_sample.TestController$$EP2E1Fn6
|     17 | index                     in     ''
|   1145 | runWorker . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run                       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . in java.lang.Thread
```

Then this one on page refresh:

```
Caused by NoClassDefFoundError: org/drools/compiler/kie/builder/impl/KieModuleCache$KModuleCache
->>  103 | createCacheBuilder in org.drools.compiler.kie.builder.impl.KieMetaInfoBuilder
```

Drools 6.2.x depends on Spring 3.2.11.RELEASE and causes this error in Grails 2.2.5 and below. AnnotationMetadataReadingVisitor moved from asm to core in 3.2. Plus, it’s probably not a good idea for Grails to be using seven more recent Spring libraries than those delivered with its release.

```
| Resolving plugin JAR dependencies.....
| Error Fatal error during compilation org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/Users/Ken/.grails/ivy-cache/org.grails/grails-core/jars/grails-core-2.0.4.jar!/org/codehaus/groovy/grails/compiler/DirectoryWatcher$FileChangeListener.class]; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/type/classreading/AnnotationMetadataReadingVisitor (Use --stacktrace to see the full trace)
```

**Comment by joshua-moore** [comment]
First off, I want to say thank you Ken for all your hard work on this plugin so far. Burt did a great job setting the stage but it's clear you have invested a lot of time and energy. I'm not a current user of the plugin though I have been keeping an eye on it because I can see the need for it in the near future. That aside, here is my opinion.

I'd say focus on making the plugin feature rich using the latest versions. Given the low number of current users of this plugin and the near release of Grails 3.0/2.5 trying to target older version of Grails, while noble, isn't critical.

I'd also like to say that if there is anything I can do to help out with this plugin, just ask. I don't mind writing documentation/samples or anything else that you feel will be helpful. I'm not a Drools expert (pun intended) but I am a very fast and eager learner with a good understanding of Drools and business rules engines in general.

**Comment by kensiprell** [comment]
Joshua, thanks for your insight. I've reworked the plugin for Drools 6.1.0.Final and Grails 2.2 and later. I’m new to Drools, so any ideas you have will be appreciated. I’m also thinking about an elegant way for a user to update the Drools version without having to copy and paste dozens of lines to his dependencies block in BuildConfig.groovy, so if you have a tip or an idea, I’d appreciate that as well.

I haven’t worked out the details yet, but I plan on adding executeFromText and fireFromText methods to DroolsService.groovy with another method to verify (https://developer.jboss.org/wiki/DroolsVerifier#jive_content_id_Using_Java https://developer.jboss.org/wiki/DroolsVerifier#jive_content_id_Using_Java) the text before committing it. I have a use case in mind where a site visitor can produce a rule set using drop-downs, etc. that can be used on the fly and persisted if necessary. 

If i don’t hear from Burt in the next day or two, I’ll submit the plugin for approval as it stands now. He’ll be the one to approve it anyway.

**Comment by kensiprell** [comment]
Plugin submitted: https://grails.org/plugins/pending/515.

**Comment by burtbeckwith** [comment]
I worked on this for a while and didn't get very far. For some reason the plugin exclusions in its BuildConfig.groovy weren't keeping the 3.2 Spring jars from evicting the 3.1 jars in a 2.0.x app, but putting them in the exclusions list for the plugin declaration in the app's BuildConfig.groovy did work.

I agree that it's better to support a wide range of Grails versions to maximize the potential user base, but perhaps this will motivate folks to upgrade :)

Having 2.2 as a minimum is quite reasonable, and it guarantees that the minimum Groovy version is 2.0, so you can write everything in Groovy with anything that would have been in Java using @CompileStatic or @TypeChecked.

I approved the plugin (the email response that it sends is buggy, so you might not receive one) so you should be all set to release when you're ready. Thanks again for taking over the plugin - I'm hoping to have a use for Drools at some point so I can use this for real.

**Comment by kensiprell** [comment]
Thanks, I published it, twice in fact. When checking the links at http://grails.org/plugin/drools I discovered that my github issues page didn't exist. Apparently forked repos don't have this service, so I changed it to https://github.com/burtbeckwith/grails-drools/issues. I can provide support unless you want to jump in.

**Comment by burtbeckwith** [comment]
How about a proper bug tracker :)  https://jira.grails.org/browse/GPDROOLS

**Comment by kensiprell** [comment]
Wow, I had no idea this was available to plugin authors. It's tough being a
grasshopper. Do I need an admin to add my other plugins? I logged in and
poked around, but I didn't see a way to add them.

I'll get the JIRA site cleaned up tonight when I get home and publish
another release. At this rate I'll be up to 1.0 by Friday with no
additional features.

**Comment by burtbeckwith** [comment]
We always used to auto-create a project per plugin, but when GitHub added support for issue tracking and it was sufficient for most projects we started leaning towards that option and adding JIRA projects by request. I'll add projects for your other plugins tomorrow.

**Comment by kensiprell** [comment]
Thanks, but after thinking about it there's no need to do that. GitHub is
working just fine. I got too excited. It's still early morning for me.
